// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class constantsGP
{
        public const string achievement_get_10_stars = "CgkI_NaTxZICEAIQAg"; // <GPGSID>
        public const string achievement_get_50_stars = "CgkI_NaTxZICEAIQBQ"; // <GPGSID>
        public const string achievement_get_40_stars = "CgkI_NaTxZICEAIQBg"; // <GPGSID>
        public const string achievement_get_30_stars = "CgkI_NaTxZICEAIQBA"; // <GPGSID>
        public const string package_name = "com.TwentyOneGames.MozgaMozg"; // <GPGSID>
        public const string leaderboard_stars_count = "CgkI_NaTxZICEAIQAQ"; // <GPGSID>
        public const string achievement_get_20_stars = "CgkI_NaTxZICEAIQAw"; // <GPGSID>

}

